In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s1=a[2:6]
print(s1)

[3 4 5 6]


In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s2=a[::2]
print(s2)

[1 3 5 7 9]


In [10]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
rev=a[::-1]
print(rev)

[9 8 7 6 5 4 3 2 1]


In [18]:
import numpy as np
a=np.array([[1,2,3,4],[4,5,6,9]])
sub=a[0:2,0:2]
print(sub)

[[1 2]
 [4 5]]


In [26]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
col=a[:,0]
print(col)

[1 5]


In [32]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
sr=a[0,:]
print(sr)

[1 2 3 4]


In [39]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,0])
print(a[1,3])

1
8


In [41]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a[5])

6


In [44]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[-2])

6


In [49]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[1:5])

[2 3 4 5]


In [51]:
import numpy as np
a=np.array([1,4,8,10,13,16,18])
print(a[a>9])

[10 13 16 18]


In [53]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8,9],[10,11,12]])
result=np.vstack((a1,a2))
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
import numpy as np
a1=np.array([[1,2],[4,5]])
a2=np.array([[7,8],[10,12]])
result=np.dstack((a1,a2))
print(result)

[[[ 1  7]
  [ 2  8]]

 [[ 4 10]
  [ 5 12]]]


In [61]:
import numpy as np
a1=np.array([1,2,3,4,5,6])
result=np.array_split(a1,2)
print(result)

[array([1, 2, 3]), array([4, 5, 6])]
