In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[19,20,21],[22,23,24]])
print("\n Array with integers:\n",a)


#import numpy as np
a=np.zeros((5,3))
print("\n Array with all zeros:\n",a)

#import numpy as np
a=np.random.random((5,3))
print("\n Random value:\n",a)


#a=np.array([[1,2,3],[4,5,6],[7,8,9],[19,20,21],[22,23,24]])
newa=a.reshape ((3,5))
print("\n Original array:\n",a)
print("\n Reshaped array[3,5]\n",newa)


#import numpy as np
a=np.arange(0,80,5)
print("\n Range value :\n",a)


 Array with integers:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [19 20 21]
 [22 23 24]]

 Array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Random value:
 [[0.51882463 0.03967183 0.4904719 ]
 [0.20491641 0.81295131 0.68979507]
 [0.20039867 0.6923417  0.69972243]
 [0.44443705 0.05252578 0.98816335]
 [0.2261635  0.14350443 0.53631646]]

 Original array:
 [[0.51882463 0.03967183 0.4904719 ]
 [0.20491641 0.81295131 0.68979507]
 [0.20039867 0.6923417  0.69972243]
 [0.44443705 0.05252578 0.98816335]
 [0.2261635  0.14350443 0.53631646]]

 Reshaped array[3,5]
 [[0.51882463 0.03967183 0.4904719  0.20491641 0.81295131]
 [0.68979507 0.20039867 0.6923417  0.69972243 0.44443705]
 [0.05252578 0.98816335 0.2261635  0.14350443 0.53631646]]

 Range value :
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]


In [29]:
import numpy as np
arr=np.array([[7,8,9],[19,20,21],[22,23,24]])
flat=arr.flatten()
print("Flattened array:\n",flat)

Flattened array:
 [ 7  8  9 19 20 21 22 23 24]


In [2]:
import numpy as np
arr=np.array([[7,8,9],[19,20,21],[22,23,24]])
print("\n Array element type:",arr.dtype)


 Array element type: int32


In [1]:
arr=np.array([[4,5,6]])
newtype=arr.astype('F')
print("\n Convert array element:\n",arr.dtype)
print("\n Converted array:",newtype.dtype)

NameError: name 'np' is not defined

In [22]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
size=len ((3,3))
print("\n size :\n",arr.size)


 size :
 9
